- color: ee0701
  description: ''
  name: bug
- color: 006b75
  description: ''
  name: chore
- color: 0366d6
  description: Pull requests that update a dependency file
  name: dependencies
- color: cccccc
  description: ''
  name: duplicate
- color: 84b6eb
  description: ''
  name: enhancement
- color: 5319e7
  description: ''
  name: feature request
- color: 128A0C
  description: ''
  name: help wanted
- color: e6e6e6
  description: ''
  name: invalid
- color: cc317c
  description: ''
  name: question
- color: 5319e7
  description: ''
  name: waiting-for-answer
- color: d4c5f9
  description: ''
  name: waiting-for-release
- color: ffffff
  description: ''
  name: wontfix
