name: Canary Release

on:
  pull_request:
    branches:
      - master
    paths:
      - ".changeset/**/*.md"

jobs:
  canary:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install Dependencies using Yarn
        run: yarn

      - name: Release Canary
        id: canary
        uses: "the-guild-org/changesets-snapshot-action@main"
        with:
          tag: alpha
          prepareScript: "yarn build"
        env:
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
